{
  "openapi": "3.0.1",
  "info": {
    "title": "API V1",
    "version": "v1"
  },
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  },
  "paths": {
    "/login": {
      "post": {
        "summary": "User login",
        "tags": [
          "Auth"
        ],
        "security": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "successful login"
          },
          "401": {
            "description": "invalid credentials"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                },
                "required": [
                  "email",
                  "password"
                ]
              }
            }
          }
        }
      }
    },
    "/admin/projects": {
      "get": {
        "summary": "List all active projects",
        "tags": [
          "Projects"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "projects found"
          },
          "401": {
            "description": "unauthorized"
          }
        }
      }
    },
    "/admin/projects/{id}/assign-project": {
      "post": {
        "summary": "Assign Project To User",
        "tags": [
          "Assign Project"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Project ID",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "project assigned"
          },
          "401": {
            "description": "unauthorized"
          },
          "404": {
            "description": "user not found"
          },
          "422": {
            "description": "unprocessable entity"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "user_id": {
                    "type": "integer"
                  }
                },
                "required": [
                  "user_id"
                ]
              }
            }
          }
        }
      }
    },
    "/admin/projects/{id}/unassign-project": {
      "post": {
        "summary": "Assign Project To User",
        "tags": [
          "Unassign Project"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Project ID",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "project unassigned"
          },
          "401": {
            "description": "unauthorized"
          },
          "404": {
            "description": "user not found"
          },
          "422": {
            "description": "unprocessable entity"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "user_id": {
                    "type": "integer"
                  }
                },
                "required": [
                  "user_id"
                ]
              }
            }
          }
        }
      }
    }
  }
}